language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-webapp-gen' ]; then cd .. && eval "mv $currentfolder generator-webapp-gen" && cd generator-webapp-gen; fi

